#!/bin/bash
#SBATCH -A SNIC2019-3-319
#SBATCH --job-name=Jackhmmer_01
#SBATCH -c 8
#SBATCH -t 12:00:00
#SBATCH --output=jack.slurm.$i.out
#SBATCH --error=jack.slurm.$i.error

#run jackhmmer
~/pfs/jackhmmer/hmmer-3.1b2/bin/jack:hmmer -A output.sto -N 5 -E 1e-3 --incE 1e-3 --cpu 8 input.fasta  /pfs/nobackup/home/c/cbass/pfs/databases/uniref90.fasta
#convert stockholm to a3m format
python /pfs/nobackup/home/m/mircomic/reformat.pyoutput.sto output.a3m
#trimming remove gaps and insertion
wait
sleep 30
 python ~/pfs/PconsC3-master/extra/arne/MSA/a3mToTrimmed.py output.a3m > output_trimmed.a3m

                                                  
