>P1;UKNP
sequence:UKNP:1    :A:350  :A::::
MKKYTAGLLICLAISIPAWFLGRLFPV----VG-GPVCAILIGMAIAPFIKGKERFRPGI-AF-----TSKKILQYAVVLLGFGMNLSVVLEKGRQSLPIILATITTSILIAVLLFRLLKIPTKSAILIGVGSSICGGSAIAAT--APV----IEAD-DEEIAQSISVIFLFNIAAALIFPALGTALGLSNEGFGLFAGTAINDTSSVTAAAAAWDGIYGSNTLEAAAIVKLTRTLAIIPITLFLAFYRTKKEQSGSGNTFQIAKIFPFFVLFFLLASVLTTVFHLPATVTGPLKDLSKFF----IIMAMAAIGTN-TNLVTLVKTGMKPILLGLCCWIGISLVSLSMQS*
>P1;5A1S
structure:5A1S: :B: :B::SALMONELLA ENTERICA:2.5:
PTDLVGGFALMFVMGAIFGEIGKRLPIFNKYIGGAPVMIFLVAAYFVYAGIFTQKEIDAISNVMDKSNFLNLFIAVLITGAILSVNRKLLLKSLLGYIPTILAGIVGASLFGIVIGLCFGIPVDRIMMLYVLPIMGGGNGAGAVPLSEIYHSVTGRSREEYYSTAIAILTIANIFAIIFAALLDMVGKKYTWLSG--EGELVRK----------------DEKAGQITHRETAVGMVLSTTCFLLAYVVAKKILP-----SIGGVSIHYFAWMVLIVAALNASGLCSPEIKAGAKRLSDFFSKQLLWVLMVGVGVCYTDLQEIIDALTFANVVIAAIIVVGAVVGAAIGG*
