>P1;UKNP
sequence:UKNP:1    :A:502  :A::::
------------------------------------------------------------------------VTFLFVLAITTVAAKFVGSNLKKYAIGFSIIFWVTMGCLMLG-NIAYIGATPDKTASYGIG-WSLGLGEMGYIIAMVVGLIIGNFFIKQADFLKEAA--------KPELFIKIGIVVLGASIAIKTLDAFGLATTIIIRGLCAVVEAYLIYWPVVYLIARKFFKFTPEWAAPLASGISICGVSAAIAT--GSA----IRAR-PVIPVILSAVIIVFVALELLLLPWLAQAFLFKDPMVAGAWMGLAVKSDGGAIASGAITDSLIRGRALRELGINWEEGWILMVATTTKVFIDIFIGVWAFILAIIWSVFPIDKNASANPGERNKVSAVDIWDRFPKFIIGFVLTFLILFLVGVNNPDGVKALSTGVNEGNAFRTIF----FGLCFFSIGLV-TNVRKLWAEGMGRIVAIYGIALFGFILWFGLFISWLF*
>P1;5A1S
structure:5A1S: :B: :B::SALMONELLA ENTERICA:2.5:
------------------------------------------------------------------------LPLYAFALITLLLSHFYNAIPTDLVGGFALMFVMGAIFGEIGKRLPIF-------NKY-IGGA--------PVMIFLVAAYFVYA-GIFTQKEIDAISNVMDKSNFLNLFIAVLITGAILSVNRKLLLKSLLGYIPTIL------AGIVGASLFGIVIGL-CFGIPVDRIMMLYVLPIMGGGNGAGAVPLSEIYHSVTGRSREEYYSTAIAILTIANIFAIIFAALLDMVGKK-YTWLSG--EGELVRK------------DE-----------------KAGQITHRETAVGMVLSTTCFLLAYVVAKKILPSIG---------------GVSIHYFAWMVLIVAALN-ASGLCSPEIKA-------GAKRLSDFFSKQLLWVLMVGVGVCYTDLQEIIDAL-TFANVVIAAIIVVGAVVGAAIGGWLI*
