>P1;UKNP
sequence:UKNP:1    :A:407  :A::::
---LLTVFIIGVLGYLL-GSIKV-KG-LSLGTSGVLIVALLFGHYGMEIPSVIREF------------GLICFVTAVGFIAGPVFFRNFKSKALSYVVIGILIIIAGAGSCVLVITLGGIPTPLAVGMMTGA-LTSTPGLAAA-IDAT----GDSMASIGYGIAY---PFGVIGVVLFVQMVPKLLNVNIPEEVSRLNQSMEKNIHHDTSPKKRIELDEFG--FFPFMIATIAGILMGKIVIPLPAGASFTLGTSGGPLLAGLVMGHFMHMGPISISVPKPTLETLREFG----LVLFLMGAGTNAGKGFVEILAQYGVALFFLGALMTLFPMVIGYVLATRIFSMDI--LNSLGSICG-GMTSTPALGTLLAVTKTEAVAASYAATYPVALIFVVLSAQFISIFLM*
>P1;5A1S
structure:5A1S: :B: :B::SALMONELLA ENTERICA:2.5:
---FALMFVMGAIFGEIGKRLPIFNKYIGGAPVMIFLVAAYFVYAGIFTQKEIDAISNVMDKSNFLNLFIAVLITGAILSVN---RKLLLKSLLGYIPTILAGIVGASLFGIVIGLCFGIPVDRIMMLYVLPIMGGGNGAGAVPLSEIYHSVTGRSREEYYSTAIAILTIANIFAIIFAALLDMVGKKYTWLSGEGELVRK-------DEKAGQITHRETAVGMVLSTTCFLLAYVVAKKILPS--IGGVSIHYFAWMVLIVAALN-ASGLCS---PEIKAGAKRLSDFFSKQLLWVLMVGVGVC--YTDLQEIIDALTFANVVIAAIIVVGAVVGAAIGGWLIGFYPIESSITAGLCMANRGGSGDLEVLSACNRMNLISYAQISSRLGGGIVLVIASIVFSMMVL*
