>P1;UKNP
sequence:UKNP:1    :A:163  :A::::
MSNFMFSLNATLPVFLVIVLGWFLMQKKMFNENFVDIINKFVFKVSLPVLLFKDIATTPIRDAF-DPKFVIFCMVGTTIMFMGIWALTSIFMKDKSMVGAFTQASARGSAAVLGIAFVQNIYGN-SGMTPLMIVSAVPLYNIYSVIILTFCANNQDHSDKSAT*
>P1;3ZUX
structure:3ZUX: :A: :A::NEISSERIA MENINGITIDIS:2.2:
IQAAGMLMSIVKMVLLPIVLGLIVHKVLGSKTEKLTDALPLVSVAAIVLIIGAVVGASKGKIMESGLLIFAVVVLHNGIGYLLGFFAAKWTGLPYDAQKALTIEVGMQNSGL-AAALAAAHFAAAPVVAVPGALFSVWHNISGSLLATYWAAKA---------*
>P1;UKNP
sequence:UKNP:1    :A:313  :A::::
--------------------------------------------------------------------------------------------------------------------------------------------------------------SATIKRAFKNILTNPIILGIAAGVPFSLLNIELPPLVLKTVTNVAQTATPMALLAVGAGFEGRKAI---KKLKPTMIATFIKLVALPAIYFPFAIAMGFRESALVAILIMVGSPTTVTCYIMAKNMGNDGVLSSSIIVMATLLSSVTLTFWIFLL*
>P1;3ZUX
structure:3ZUX: :A: :A::NEISSERIA MENINGITIDIS:2.2:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------NILSKISSFIGKTFSLWAALFAAAAFFAPDT-FKWAGPYIPWLLGIIMFGMGLTLKPSDFDILFKHPKVVIIGVIAQFAIMPATAWCLSKLLNLPAEIAVGVILVGCCPGGTASNVMTYLARGNVALSVAVTSVSTLTSPLLTPAIFLML*
