>P1;UKNP
sequence:UKNP:1    :A:373  :A::::
---FPAVLQWLILLLASLALGFGLLAFHIPAALLLGPMIVGVTL-GLLGASVRIPKPLFIGA-----Q-----AVLGCMIAQSLSPSMLTPLLADWPLILLVLLATLLASGISGWCLVRFSDLPGPTGAW-GASP---GGASAMVA-MAGD----FGADV--RLVAFM--QYLRVLFVATAAAVVARIGLGDEAGQGSAT------------LNWFPPLDWRFLATLAVAAAGAWLGPRLR---------IPSGALLLPMIIGAALHSSGAMALQVPEWLLALAY-----TLIGWSVGLRFTRPILLLALRTL-PQMLVSIAALMLFCGLLAWMLTCFLPVDMMTAYLA-----TSPGGLDTVAIIAAGSRVD*
>P1;5A1S
structure:5A1S: :B: :B::SALMONELLA ENTERICA:2.5:
---TDLVGGFALMFVMGAIFGEIGKRLPIFNKYIGGAPVMIFLVAAYFVYAGIFTQKEIDAISNVMDKSNFLNLFIAVLITGAILSVNRKLLLKSLLGYIPTILAGIVGASLFGIVIGLCFGIPVDRIMMLYVLPIMGGGNGAGAVPLSEIYHSVTGRSREEYYSTAIAILTIANIFAIIFAALLDMVGKKYTWLSGEGELVRK-------DEKAGQITHRETAVGMVLSTTCFLLAYVVAKKILPSIGGVSIHYFAWMVLIVAALNASGLCSPEIKAGAKRLSDFFSKQLLWVLMVGVGVCYTDLQEIIDALTFANVVIAAIIVVGAVVGAAIGGWLIGFYPIESSITAGLCMANRGGSGDLEVLSACNRMN*
