>P1;UKNP
sequence:UKNP:1    :A:441  :A::::
--LPIANDAVVLGLLMVCLGFVFYTSSQKTKFWKV-FYTIFPALLICYILPAILNSIGIISNK-TSNLYFV-----ASRYLLPAALILMTLSIDLRAVFNLGAKALIMFFAGTFGIIIGGPLAILIVSTFMPEAVGGVGPDAVWRGLSTVAGSWIGGGANQAAM--LEI----YKYN-PEKYGAMV---IVDIVVANIWMAFLLFGIGKSDKIDRWLKADNSSIEDLKNRVISFSEKTKKQPTLVDYKVMLALAFGGVGLSHFGADIITDFLKSNFESIRNAQSATSFFGDTFFWLVTFATLIGILLSFTKARNYEGAGASKLGSVF----IYVLVATIGMK-MNLTQVFDN--PGLLLVGLIWMAIHVLVMFLVAKIIRAPYFFLAVG---SKANVGGAASAPVVASAFHPSLATVGVLLAVLGYVV-GTYGAMLSAYLM*
>P1;5A1S
structure:5A1S: :B: :B::SALMONELLA ENTERICA:2.5:
--AIPTDLVGGFALMFVMGAIFGEI-GKRLPIFNKYIGG---APVMIFLVAAYFVYAGIFTQKEIDAISNVMDKSNFLNLFIAVLITGAILSVNRKLLLKSLLGYIPTILAGIVGASLFGIVIGLCFG------------IPVDRIMMLYVLPIMGGGNGAGAVPLSEIYHSVTGRSREEYYSTAIAILTIANIFAIIFAALLDM------VGKKYTWLSGEGELVRK-------DEKAGQITHRETAVGMVLSTTCFLLAYVVAKKILPSIG-------------GVSIHYFAWMVLIVAALN-ASGLCSPEIKA--GAKRLSDFFSKQLLWVLMVGVGVCYTDLQEIIDALTFANVVIAAIIVVGAVVGAAIGGWLIGFYPIESSITAGLCMANRGGSGDLEVLSACNRMNLISYAQISSRLGGGIVLVIASIVFSMMV*
